### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kibertoad** [gkampitakis/fastify-custom-healthcheck#12]
Would be awesome to have new version with fastify 4 support!

**Comment by gkampitakis** [comment]
Happy to, but I am not sure what should be changed to support it. Or do you mean just to bump the version and release a `3.0.0`.

**Comment by kibertoad** [comment]
You are already running tests on v4, so if they are passing, it should be good.

**Comment by gkampitakis** [comment]
Thanks for checking :smile: Going to close this issue then if this is not for just releasing a version.

**Comment by kibertoad** [comment]
It is specifically for releasing a version. Is there any timeline for doing so?

**Comment by gkampitakis** [comment]
oh sorry, my misunderstanding then. I could

**Comment by gkampitakis** [comment]
https://github.com/gkampitakis/fastify-custom-healthcheck/commit/a242dc20a297d8f7b4fbfd3681bdc3faa5b16093 Done :tada:
