### ISSUE TITLE
Make schema optional and/or overrideable

### ISSUE THREAD

**Issue by kibertoad** [gkampitakis/fastify-custom-healthcheck#14]
Considering that users of this library might be relying on custom type providers (e. g. Zod or Typebox), always setting schema on the route may break this plugin for them.

Being able to remove schema or replace with custom-written one (based on a custom type provider used), would make the plugin more widely compatible.

**Comment by kibertoad** [comment]
@gkampitakis I can send a PR for this, if you approve of this change.

**Comment by gkampitakis** [comment]
hey 👋  thanks for opening this issue. I will admit I am not really up to speed with the latest fastfiy so I will probably won't be able to address this issue in a time. 

That said your PR would be more than welcome 😊

**Comment by kibertoad** [comment]
PR created!
Maybe you would be open to inviting additional maintainers for the repo? Lokalise would be happy to help with maintaining the project, represented by myself and @lokankr :)

**Comment by gkampitakis** [comment]
hey, I built this almost two years ago when I was actively working with fastfiy and needed this functionality, right now I am pretty left behind on what's current.

If this is a project you are using or you are interested in I am more than happy to add you as maintainers, although I am unsure what's the process for inviting on gh and on npm.

**Comment by kibertoad** [comment]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

https://stackoverflow.com/questions/53756814/how-to-add-contributors-collaborators-to-a-npm-package

and yes, we plan to use the package very actively!

**Comment by gkampitakis** [comment]
Invites for gh have been sent 😄 if you want to share npm usernames I ll short out npm as well

**Comment by kibertoad** [comment]
kibertoad for me, will ask Andreas for his when he is back from sick leave

**Comment by gkampitakis** [comment]
Done tell me if everything is okay on your side. Thanks again. If you want to give a shot for the new version as well to check everything is fine

**Comment by kibertoad** [comment]
@gkampitakis It all works, thank you!
