### ISSUE TITLE
[FEATURE REQUEST] Add CPU usage

### ISSUE THREAD

**Issue by go4cas** [gkampitakis/fastify-custom-healthcheck#18]
Please add the CPU Usage (`process.cpuUsage()`) to the stats.

**Comment by kibertoad** [comment]
@go4cas isn't it already possible?

**Comment by go4cas** [comment]
Yes, with `process.cpuUsage()`.

**Comment by go4cas** [comment]
@kibertoad, I did a PR for this a few days ago. Are you okay to merge?
